### ISSUE TITLE
Live Music Player issue

### ISSUE THREAD

**Issue by RTMKXXIII** [MarshmallowAndroid/UmaMusumeExplorer#11]
Greeting, developer. Very good program ,love from center training school
could you check [うまぴょい伝説] in Live Music Player? When I trying to click it , program will show this error message.
==================================================================================
Specified argument was out of the range of valid values. (Parameter 'index')。

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.UnitSetupForm.AddUnitMembers() in C:\Users\jacob\source\repos\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\UnitSetupForm.cs:line 50
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.PlayerForm.SetupUnit() in C:\Users\jacob\source\repos\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\PlayerForm.cs:line 262
   at UmaMusumeExplorer.Controls.LiveMusicPlayer.PlayerForm.SetupButton_Click(Object sender, EventArgs e) in C:\Users\jacob\source\repos\UmaMusumeExplorer\UmaMusumeExplorer\Controls\LiveMusicPlayer\PlayerForm.cs:line 119
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
====================================================================================
All other music is fine, Thank you again for your great work.

**Comment by MarshmallowAndroid** [comment]
Hello and thank you for your kind words! I have published a release that fixes the issue.
